[project]
name = "tee1-3"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "invoke>=2.2.1",
    "livereload>=2.7.1",
    "pelican[markdown]>=4.11.0",
]
